debug: false

public:
  directory: public

cache:
  directory: _cache
  auto_reload: true

templates:
  directory: templates
  extension: html
  notfound: _errors/404
  error: _errors/500
  
prontotype:
  server: server.php
  templates: templates
  plugins: vendor/prontotype/plugins
