debug: false

public:
  directory: public

templates:
  directory: templates
  extension: html

routes:
  example:
    match: '/{category}'
    template: 'about'

data:
  directory: data
   
prontotype:
  server: server.php
