public:
  directory: public

cache:
  directory: _cache
  auto_reload: true

templates:
  directory: templates
  extension: html

plugins:
  directory: vendor/prontotype/plugins
  
prontotype:
  server: server.php
  templates: templates
