debug: false

short_urls: true

public:
  directory: public

cache:
  directory: _cache
  auto_reload: true

templates:
  directory: templates
  extension: html
  notfound: _errors/404
  error: _errors/500

routes:
  example:
    match: '/category/{category}'
    template: 'about'
  
prontotype:
  server: server.php
  templates: templates
  plugins: vendor/prontotype/plugins
