debug: false

public:
  directory: public

templates:
  directory: templates
  extension: html
  notfound: _errors/404
  error: _errors/500

routes:
  example:
    match: '/category/{category}'
    template: 'about'

data:
  directory: data
   
prontotype:
  server: server.php
