public:
  directory: public

cache:
  directory: _cache
  auto_reload: true

templates:
  directory: templates
  extension: html
  
prontotype:
  server: server.php
  templates: templates
  plugins: vendor/prontotype/plugins
